[getList]
SELECT
     `hrmis_appointmentpermanent`.*,
     `status`.`name` AS status_name,
     `status`.`description` AS status_description,
     `status`.`code` AS status_code,
     `status`.`istenure` AS status_istenure,
     `status`.`state` AS status_state,
     `status`.`recordlog_datecreated` AS status_recordlog_datecreated,
     `status`.`recordlog_createdbyuserid` AS status_recordlog_createdbyuserid,
     `status`.`recordlog_createdbyuser` AS status_recordlog_createdbyuser,
     `status`.`recordlog_dateoflastupdate` AS status_recordlog_dateoflastupdate,
     `status`.`recordlog_lastupdatebyuserid` AS status_recordlog_lastupdatebyuserid,
     `status`.`recordlog_lastupdatebyuser` AS status_recordlog_lastupdatebyuser,
     `status`.`oldid` AS status_oldid,
     `status`.`isapplicableforplantillaposition` AS status_isapplicableforplantillaposition,
     `status`.`hasleave` AS status_hasleave,
     `status`.`leaveearning` AS status_leaveearning,
     `status`.`hasstepincrement` AS status_hasstepincrement,
     `status`.`isgovernmentservice` AS status_isgovernmentservice,
     `status`.`compensationtype` AS status_compensationtype,
     `status`.`compensationearning` AS status_compensationearning,
     `status`.`stepincrementyearsmultiplicity` AS status_stepincrementyearsmultiplicity,
     `status`.`appointmentreportdoc` AS status_appointmentreportdoc,
     `status`.`isapplicableforsalaryscheduleadjustment` AS status_isapplicableforsalaryscheduleadjustment,
     `status`.`plantillatype` AS status_plantillatype,
     `status`.`sortposition` AS status_sortposition,
     `natureofappointment`.`name` AS natureofappointment_name,
     `natureofappointment`.`description` AS natureofappointment_description,
     `natureofappointment`.`code` AS natureofappointment_code,
     `natureofappointment`.`pastverb` AS natureofappointment_pastverb,
     `natureofappointment`.`hasappointmentissued` AS natureofappointment_hasappointmentissued,
     `natureofappointment`.`state` AS natureofappointment_state,
     `natureofappointment`.`recordlog_datecreated` AS natureofappointment_recordlog_datecreated,
     `natureofappointment`.`recordlog_createdbyuserid` AS natureofappointment_recordlog_createdbyuserid,
     `natureofappointment`.`recordlog_createdbyuser` AS natureofappointment_recordlog_createdbyuser,
     `natureofappointment`.`recordlog_dateoflastupdate` AS natureofappointment_recordlog_dateoflastupdate,
     `natureofappointment`.`recordlog_lastupdatebyuserid` AS natureofappointment_recordlog_lastupdatebyuserid,
     `natureofappointment`.`recordlog_lastupdatebyuser` AS natureofappointment_recordlog_lastupdatebyuser,
     `natureofappointment`.`natureofappointment` AS natureofappointment_natureofappointment,
     `pds`.`state` AS pds_state,
     `pds`.`pdsno` AS pds_pdsno,
     `pds`.`versionno` AS pds_versionno,
     `pds`.`person_objid` AS pds_person_objid,
     `pds`.`maidenname` AS pds_maidenname,
     `pds`.`person_name` AS pds_person_name,
     `pds`.`person_lastname` AS pds_person_lastname,
     `pds`.`person_firstname` AS pds_person_firstname,
     `pds`.`person_middlename` AS pds_person_middlename,
     `pds`.`person_birthdate` AS pds_person_birthdate,
     `pds`.`person_birthplace` AS pds_person_birthplace,
     `pds`.`person_gender` AS pds_person_gender,
     `pds`.`person_civilstatus` AS pds_person_civilstatus,
     `pds`.`person_citizenship` AS pds_person_citizenship,
     `pds`.`person_phoneno` AS pds_person_phoneno,
     `pds`.`person_mobileno` AS pds_person_mobileno,
     `pds`.`person_email` AS pds_person_email,
     `pds`.`nameextension` AS pds_nameextension,
     `pds`.`prenametitle` AS pds_prenametitle,
     `pds`.`postnametitle` AS pds_postnametitle,
     `pds`.`residential_address` AS pds_residential_address,
     `pds`.`residentialzipcode` AS pds_residentialzipcode,
     `pds`.`permanent_address` AS pds_permanent_address,
     `pds`.`permanentzipcode` AS pds_permanentzipcode,
     `pds`.`height` AS pds_height,
     `pds`.`weight` AS pds_weight,
     `pds`.`bloodtype` AS pds_bloodtype,
     `pds`.`gsisid` AS pds_gsisid,
     `pds`.`pagibigid` AS pds_pagibigid,
     `pds`.`philhealth` AS pds_philhealth,
     `pds`.`sss` AS pds_sss,
     `pds`.`tin` AS pds_tin,
     `pds`.`employeeno` AS pds_employeeno,
     `pds`.`recordlog_datecreated` AS pds_recordlog_datecreated,
     `pds`.`recordlog_createdbyuserid` AS pds_recordlog_createdbyuserid,
     `pds`.`recordlog_createdbyuser` AS pds_recordlog_createdbyuser,
     `pds`.`recordlog_dateoflastupdate` AS pds_recordlog_dateoflastupdate,
     `pds`.`recordlog_lastupdatedbyuserid` AS pds_recordlog_lastupdatedbyuserid,
     `pds`.`recordlog_lastupdatedbyuser` AS pds_recordlog_lastupdatedbyuser,
     `paygradeandstepincrement`.`grade` AS paygradeandstepincrement_grade,
     `paygradeandstepincrement`.`step` AS paygradeandstepincrement_step,
     `paygradeandstepincrement`.`state` AS paygradeandstepincrement_state,
     `paygradeandstepincrement`.`recordlog_datecreated` AS paygradeandstepincrement_recordlog_datecreated,
     `paygradeandstepincrement`.`recordlog_createdbyuserid` AS paygradeandstepincrement_recordlog_createdbyuserid,
     `paygradeandstepincrement`.`recordlog_createdbyuser` AS paygradeandstepincrement_recordlog_createdbyuser,
     `paygradeandstepincrement`.`recordlog_dateoflastupdate` AS paygradeandstepincrement_recordlog_dateoflastupdate,
     `paygradeandstepincrement`.`recordlog_lastupdatebyuserid` AS paygradeandstepincrement_recordlog_lastupdatebyuserid,
     `paygradeandstepincrement`.`recordlog_lastupdatebyuser` AS paygradeandstepincrement_recordlog_lastupdatebyuser,
     `paygradeandstepincrement`.`oldid` AS paygradeandstepincrement_oldid,
     `org`.`name` AS org_name,
     `org`.`code` AS org_code,
     `org`.`description` AS org_description
FROM 
     `hrmis_appointmentpermanent` `hrmis_appointmentpermanent`
     INNER JOIN `references_tblemptemploymentstatus` `status` ON `status`.`objid` = `hrmis_appointmentpermanent`.`status_objid`
     INNER JOIN `hrmis_pds` pds ON `hrmis_appointmentpermanent`.`pds_objid` = `pds`.`objid`
     INNER JOIN `references_tblappointmententrycode` natureofappointment ON `hrmis_appointmentpermanent`.`natureofappointment_objid` = `natureofappointment`.`objid`
     INNER JOIN `hrmis_tblemploymentplantilla` plantilla ON `hrmis_appointmentpermanent`.`plantilla_objid` = `plantilla`.`objid`
     INNER JOIN `references_tblpaygradeandstepincrement` paygradeandstepincrement ON `hrmis_appointmentpermanent`.`paygradeandstepincrement_objid` = `paygradeandstepincrement`.`objid`
     INNER JOIN `references_tblorganizationunit` org ON org.`orgunitid` = plantilla.`org_orgunitid`
WHERE `hrmis_appointmentpermanent`.`objid` IS NOT NULL
${filter}